version: 2
updates:
  # Mises à jour des dépendances Python (pip)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  # Mises à jour des actions GitHub elles-mêmes
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"